language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "nightly"  # nightly build

before_install:
  - PARENTDIR=$(pwd)
  - DAILY_FILE="SPY_$(date --date='1 days ago' +'%Y%m%d').avro"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run some tests
script:
  - cd ${PARENTDIR}/tdameritrade-market-data 
  - python td_get_price_history.py -s SPY -S "$(date --date='1 days ago' +'%Y-%m-%d 00:00:00')" -E "$(date --date='1 days ago' +'%Y-%m-%d 23:59:00')" -e True -k ${TD_API_KEY}
  - avro write --schema=config/td-schema.json --input-type=json -o charts/${DAILY_FILE} charts/SPY.jsonl

after_success: |
  if [ -n "$GITHUB_TOKEN" -a "x$TRAVIS_BRANCH" = "xmaster" ]; then
    cd ${PARENTDIR}/tdameritrade-market-data
    git clone -q https://hn-antoine:${GITHUB_TOKEN}@github.com/hn-antoine/datalake-tdameritrade.git
    mv charts/${DAILY_FILE} datalake-tdameritrade/
    cd datalake-tdameritrade
    git add ${DAILY_FILE}
    git -c user.name='hn-antoine' -c user.email='91835230+hn-antoine@users.noreply.github.com' commit -m "add ${DAILY_FILE}" .
    git push -f -q
  fi
