# This workflow will upload a daily data into repo datalake_tdameritrade

name: Upload Python Package

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 23 * * *'
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/learn-github-actions/environment-variables
    # env:   
      
    steps:
    - name: setup env variables
      run: |
        echo "PARENTDIR=$(pwd)" >> $GITHUB_ENV
        echo "DAILY_FILE=SPY_$(date --date='1 days ago' +'%Y%m%d').avro" >> $GITHUB_ENV
        
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt       
    - name: Download data of previous day
      run: |
        cd tdameritrade-market-data 
        python td_get_price_history.py -s SPY -S "$(date --date='1 days ago' +'%Y-%m-%d 00:00:00')" -E "$(date --date='1 days ago' +'%Y-%m-%d 23:59:00')" -e True -k ${{ secrets.TD_API_KEY }}         
        avro write --schema=config/td-schema.json --input-type=json -o charts/${DAILY_FILE} charts/SPY.jsonl

    - name: Deploy files to datalake_tdameritrade
      run: |
        cd ${PARENTDIR}/tdameritrade-market-data
        git clone -q https://hn-antoine:${GITHUB_TOKEN}@github.com/hn-antoine/datalake-tdameritrade.git
        mv charts/${DAILY_FILE} datalake-tdameritrade/
        cd datalake-tdameritrade
        git add ${DAILY_FILE}
        git -c user.name='hn-antoine' -c user.email='91835230+hn-antoine@users.noreply.github.com' commit -m "add ${DAILY_FILE}" . 
        if [ "x$GITHUB_REF" == "xdaily" ]; then git push -f -q; fi
